version: '3'
services:
  mongodb:
    image : mongo:4.2.16-rc0-bionic
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin
  
  mongo-express:
    image: mongo-express:1.0.0-alpha.4
    ports:
      - 8080:8081
    environment:
      - ME_CONFIG_MONGODB_ADMINUSERNAME=admin
      - ME_CONFIG_MONGODB_ADMINPASSWORD=admin
      - ME_CONFIG_MONGODB_SERVER=mongodb
      
    depends_on:
      - mongodb
  
  my-app:
    image : satishkumar313/demo_app:1.2
    ports:
      - 5000:5000


      